-- =============================================================================
--  This file used to hold a hand-maintained copy of the schema. It no longer
--  does, because two copies of a schema drift apart and then neither can be
--  trusted.
--
--  The schema now lives in one place, and it is the file the application
--  actually runs at startup:
--
--      backend/src/main/resources/db/schema.sql
--
--  Read that. It carries the full DDL, the reasoning behind the column order,
--  the naming convention, and how to start over.
-- =============================================================================
